# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a2c1c8f6847d73daf77699e3919c30ef1acf311d003fcfc523c27bb4f97af831c1d23a936325c9fa9dc025c32b39392f067b3039c3e52c50a9763d399ebe256

test:
  secret_key_base: 5e9adbb46ea9652d2ab608fce61194c601c82da287f6cd56c592d2b10722943ca6b5999fb1eea652cac132ebe536cf8b7ebe02024f3c589928da73abd66cc5f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
